### ISSUE TITLE
Command failed: gm convert: No decode delegate for this image format

### ISSUE THREAD

**Issue by Suyash-Purwar** [yakovmeister/pdf2image#102]
I am getting this error when I use the exact code written in the npm documentation's first example.

```
Error: Command failed: gm convert: No decode delegate for this image format (C:\Users\acer\AppData\Local\Temp\gmnP1bMn).

    at ChildProcess.onExit (D:\Suyash\Work\pennywise\pdf-manipulation\node_modules\gm\lib\command.js:301:17)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (D:\Suyash\Work\pennywise\pdf-manipulation\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  code: 1,
  signal: null
}
```

I am using windows 10 64-bit architecture and have installed the following and added them in window's path:

- GraphicsMagick-1.3.36-Q8-win64-dll
- gs952w64

What am I doing wrong? @yakovmeister

**Comment by yakovmeister** [comment]
Hi @Suyash-Purwar , will you be able to provide a snippet of your code?

**Comment by Suyash-Purwar** [comment]
Thanks for responding! Here's the snippet

```
const { fromPath } = require('pdf2pic');

const options = {
  density: 100,
  saveFilename: "untitled",
  savePath: "./images",
  format: "png",
  width: 600,
  height: 600
};

// Path to pdf is different in my case but  it's of this exact format
const storeAsImage = fromPath("/path/to/pdf/sample.pdf", options);
const pageToConvertAsImage = 1;

storeAsImage(pageToConvertAsImage).then((resolve) => {
  console.log("Page 1 is now converted as image");

  return resolve;
});
```

**Comment by yakovmeister** [comment]
@Suyash-Purwar , have you tried the solution mentioned in this page? https://stackoverflow.com/questions/66732199/how-to-fix-the-graphicsmagik-error-gm-convert-no-decode-delegate-for-this-imag

**Comment by Suyash-Purwar** [comment]
Hey @yakovmeister 

I am having a problem installing the fonts. Below is the image of the prompt.
![Capture](https://user-images.githubusercontent.com/33785844/124860736-d766e080-dfcf-11eb-9eb7-15b66f284a99.PNG)

**Comment by yakovmeister** [comment]
@Suyash-Purwar Hmmm.. I'm not sure why it's not installing. Can you try converting those fonts to .ttf format and install the .ttf font format?

**Comment by Suyash-Purwar** [comment]
I'll try and will get back to you asap. Thanks a lot!

**Comment by Suyash-Purwar** [comment]
@yakovmeister  Converted the .pfb files to .tff format and installed them. Error is still there. 
This is the pdf I'm trying to convert.
[input-pdf.pdf](https://github.com/yakovmeister/pdf2image/files/6804731/input-pdf.pdf)

**Comment by LuisSic** [comment]
I'm getting the same issue with a specific pdf. Did you find any solution for this? @Suyash-Purwar.
I'm using Ubuntu 20.04 LTS and GraphicsMagick 1.3.35 2020-02-23

**Comment by hunha** [comment]
I've got the same issue. Using this GraphicsMagick version fix the problem: **GraphicsMagick-1.3.31-Q8-win64-dll**
Maybe the newer version isn't compatible with gs952w64.
