### ISSUE TITLE
Error: Command failed:

### ISSUE THREAD

**Issue by hansaliyad1** [yakovmeister/pdf2image#149]
Hello,

I am getting below error and I am not understanding what I am doing wrong. I will really appreciate if someone can help me out with this.

```
Error: Command failed:
    at ChildProcess.onExit (E:\APPS\temp\FCBatchManagerTs\node_modules\gm\lib\command.js:301:17)
    at ChildProcess.emit (node:events:394:28)
    at ChildProcess.cp.emit (E:\APPS\temp\FCBatchManagerTs\node_modules\gm\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Comment by rafaelgrilli92** [comment]
Same issue here

**Comment by underfisk** [comment]
If anyone is looking/encountered this issue, it happens when there's not enough memory for **GM** to allocate. You can either bump your server resources or attempt to optimize pdf2pic and reduce the image **density** and **quality**
