### ISSUE TITLE
Command failed: gm convert

### ISSUE THREAD

**Issue by enoh-barbu** [yakovmeister/pdf2image#157]
I'm trying to convert a PDF from a buffer 

```
const storeAsImage = fromBuffer(
      toBuffer(pdfBytes),
      {
          savePath: path.resolve(__dirname, '../flatten-images'),
          format: 'png'
      }
  );
  await storeAsImage(1);
```

but I get an error in the console

```
Error: Command failed: gm convert: Unable to open file (C:\Windows\TEMP\gmQXbr1D) [No such file or directory].

    at ChildProcess.onExit (D:\project\node_modules\gm\lib\command.js:301:17)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:475:12)
    at ChildProcess.cp.emit (D:\project\node_modules\gm\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  signal: null
}
```

I'm using node v16, windows 10 and I do have installed graphicsmagick & ghostscript

**Comment by Vrajs16** [comment]
Which version of Ghostscript are you using for windows. According to [this](https://github.com/yakovmeister/pdf2image/blob/master/docs/gm-installation.md), you need version 9.52 which you can find from the link.

**Comment by enoh-barbu** [comment]
yes, I was using 9.52

**Comment by kdash1228** [comment]
@enoh-barbu - Were you able to figure out a workaround or a solution for this error message?

**Comment by enoh-barbu** [comment]
@kdash1228 not really. I dropped the library, I'm using only ghostscript commands now for achieving the same result
