### ISSUE TITLE
Could not execute GraphicsMagick/ImageMagick

### ISSUE THREAD

**Issue by saurabh28** [yakovmeister/pdf2image#19]
Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%p" "filename.pdf" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/Users/saurabh/Desktop/IMap/node_modules/gm/lib/command.js:232:12)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by yakovmeister** [comment]
graphicmagick needs to be installed first before you can use this module. You can follow the instruction from http://www.graphicsmagick.org/README.html
