### ISSUE TITLE
Can't find ./dist/index.js when ./dist/index.min.js exists

### ISSUE THREAD

**Issue by notbrain** [yakovmeister/pdf2image#24]
Just built a project that was using pdf2pic, and came across an odd build error. 

    Error: Cannot find module './dist/index.js'
        at Function.Module._resolveFilename (module.js:548:15)
        at Function.Module._load (module.js:475:25)
        at Module.require (module.js:597:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/my-utility/node_modules/pdf2pic/index.js:3:18)
        at Module._compile (module.js:653:30)
        at Object.Module._extensions..js (module.js:664:10)
        at Module.load (module.js:566:32)
        at tryModuleLoad (module.js:506:12)
        at Function.Module._load (module.js:498:3)

When I look in pdf2pic in `node_modules`, I see `node_modules/pdf2pic/dist/index.min.js`, _not_ `index.js`. Is this intentional and I'm missing some config or is this a bug? It's like the published pdf2pic distribution is broken and it's not looking for the minified version.

**Comment by yakovmeister** [comment]
Hi, I didn't notice it the time I made changes with the transpiler, a fix has been pushed and published, that should work now. Thanks :+1:
