### ISSUE TITLE
Transpiler issue? Can only use "1.2.6"

### ISSUE THREAD

**Issue by notbrain** [yakovmeister/pdf2image#25]
If I specify "^1.2.6" or "^1.3.1" I get this:

    Error: Cannot find module '@babel/polyfill'
        at Function.Module._resolveFilename (module.js:548:15)
        at Function.Module._load (module.js:475:25)
        at Module.require (module.js:597:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/ocr-utility/node_modules/pdf2pic/dist/index.min.js:1:160)
        at Module._compile (module.js:653:30)
        at Object.Module._extensions..js (module.js:664:10)
        at Module.load (module.js:566:32)
        at tryModuleLoad (module.js:506:12)
        at Function.Module._load (module.js:498:3)

**Comment by yakovmeister** [comment]
sorry about that, you can use the older version using `npm i pdf2pic@1.2.6 -S`

**Comment by notbrain** [comment]
Yep, that's what I'm doing. Thanks

**Comment by yakovmeister** [comment]
didn't really have much time to tinker around, new patch has been published. `1.3.2` should fix this issue. Closing this now.
