### ISSUE TITLE
TypeError: PDF2Pic is not a constructor

### ISSUE THREAD

**Issue by totorelmatador** [yakovmeister/pdf2image#28]
Hi everyone,
I'm trying to use pdf2pic as the example : 
```
let PDF2Pic = require('pdf2pic').default
let converter = new PDF2Pic({
  density: 100,           // output pixels per inch
  savename: "untitled",   // output file name
  savedir: "./images",    // output file location
  format: "png",          // output file format
  size: 600               // output size in pixels
})

// by default the first page of the pdf will be converted
// to image
converter.convert("/path/to/pdf/sample.pdf")
  .then(resolve => {
    console.log("image converted successfully")
  })
```
But it returns the following error : 
```
/mnt/c/Users/totorelmatador/Desktop/test/test.js:3
let converter = new PDF2Pic({
                ^

TypeError: PDF2Pic is not a constructor
    at Object.<anonymous> (/mnt/c/Users/totorelmatador/Desktop/test/test.js:3:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

I do not understand what is the source of the problem... I tried to remove the `.defaut` from the `require` as follow : 

`let PDF2Pic = require('pdf2pic')`

But I obtain this error : 

```
(node:2145) UnhandledPromiseRejectionWarning: Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%p" "./extracted.pdf" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/gm/lib/command.js:232:12)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
(node:2145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2145) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2145) UnhandledPromiseRejectionWarning: Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "-density" "100x100" "-quality" "75" "-[0]" "-resize" "600x" "-compress" "jpeg" "./tattoo_process/untitled_1.png" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/gm/lib/command.js:232:12)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
(node:2145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Can someone help me ? :D 
Thank you !

**Comment by AntonC9018** [comment]
Install Ghostscript https://www.ghostscript.com/download/gsdnld.html and GraphicsMagick http://www.graphicsmagick.org/download.html

**Comment by gopeter** [comment]
I have the same problem and installed both Ghostscript and GraphicsMagick. Both tools are available in the command line also (via `ghostscript` and `convert`).

**Comment by AntonC9018** [comment]
@gopeter remove .default. It worked for me

**Comment by totorelmatador** [comment]
Hi @AntonC9018 ! Thank you for your help. I did install Ghostscript and GraphicsMagick, but now I have the following error :

```
(node:4591) UnhandledPromiseRejectionWarning: Error: Command failed: gm identify: Coder did not return an image (this is a bug, please report it!) (ThePdfIWant.pdf)
[No such file or directory].
gm identify: Request did not return an image.

    at ChildProcess.onExit (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:4591) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4591) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4591) UnhandledPromiseRejectionWarning: Error: Command failed: gm convert: Coder did not return an image (this is a bug, please report it!) (/tmp/gmykk9lm) [No such file or directory].

    at ChildProcess.onExit (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:4591) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
But the file `ThePdfIWant.pdf` does exist... Do you have any idea how I can face this issue ?
Thank you for your time !

**Comment by AntonC9018** [comment]
@totorelmatador Seems like you didn't get the path right. Can it be that you mixed up the path to the file?

**Comment by gopeter** [comment]
> @gopeter remove ".default". It worked for me.

Worked like a charm, thanks!

**Comment by totorelmatador** [comment]
@AntonC9018  No I don't think so. To be sure I precise the full path:

```
let PDF2Pic = require('pdf2pic')
let converter = new PDF2Pic({
  density: 100,           // output pixels per inch
  savename: "untitled",   // output file name
  //savedir: "./images",    // output file location
  format: "png",          // output file format
  size: 600               // output size in pixels
})

// by default the first page of the pdf will be converted
// to image
converter.convert("C:/Users/totorelmatador/Desktop/test/ThePdfIWant.pdf")
  .then(resolve => {
    console.log("image converted successfully")
  })
```

But I obtain the same kind of error: 

```
(node:104) UnhandledPromiseRejectionWarning: Error: File supplied cannot be found
    at t.value (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:7590)
    at t.<anonymous> (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:2888)
    at tryCatch (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:428)
    at a (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:646)
    at /mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:739
    at new Promise (<anonymous>)
    at t.<anonymous> (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:587)
    at t._createClass.value (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:3443)
    at Object.<anonymous> (/mnt/c/Users/totorelmatador/Desktop/test/test.js:12:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
(node:104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The weird thing is that I obtain the same error when I get a wrong path... But I swear the file exists and this is the right path :D (I tried with several files by the way)

**Comment by totorelmatador** [comment]
I tried to find where the error `Error: File supplied cannot be found` comes from. I checked in the file `/mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js` and I found the following line:
```
{key:"fileExists",value:function(e){if(!fs.existsSync(e))throw new Error("File supplied cannot be found");return!0}}
```
Then I ran the following code 
```
let PDF2Pic = require('pdf2pic')
let converter = new PDF2Pic({
  density: 100,           // output pixels per inch
  savename: "untitled",   // output file name
  //savedir: "./images",    // output file location
  format: "png",          // output file format
  size: 600               // output size in pixels
})

console.log(fs.existsSync("C:/Users/totorelmatador/Desktop/test/ThePdfIWant.pdf"))

// by default the first page of the pdf will be converted
// to image
converter.convert("C:/Users/totorelmatador/Desktop/test/ThePdfIWant.pdf")
  .then(resolve => {
    console.log("image converted successfully")
  })
```

It seems that the file doesn't exist (`false` appears). But I don't understand why. It's even more confusing for me because when I start Debugging, the line `console.log(fs.existsSync("C:/Users/totorelmatador/Desktop/test/ThePdfIWant.pdf"))` returns `true`...

**Comment by totorelmatador** [comment]
@AntonC9018 I tried several things, and I observed that the error:
```
(node:4591) UnhandledPromiseRejectionWarning: Error: Command failed: gm identify: Coder did not return an image (this is a bug, please report it!) (ThePdfIWant.pdf)
[No such file or directory].
gm identify: Request did not return an image.

    at ChildProcess.onExit (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:4591) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4591) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4591) UnhandledPromiseRejectionWarning: Error: Command failed: gm convert: Coder did not return an image (this is a bug, please report it!) (/tmp/gmykk9lm) [No such file or directory].

    at ChildProcess.onExit (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:4591) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

appears when the path is correct. When it is not, the error is:
```
(node:104) UnhandledPromiseRejectionWarning: Error: File supplied cannot be found
    at t.value (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:7590)
    at t.<anonymous> (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:2888)
    at tryCatch (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:428)
    at a (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:646)
    at /mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:739
    at new Promise (<anonymous>)
    at t.<anonymous> (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:587)
    at t._createClass.value (/mnt/c/Users/totorelmatador/Desktop/test/node_modules/pdf2pic/dist/index.min.js:1:3443)
    at Object.<anonymous> (/mnt/c/Users/totorelmatador/Desktop/test/test.js:12:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
(node:104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gopeter** [comment]
@totorelmatador maybe some issues with the path itself? Have you tried backslashes (seems that you're using Windows?): https://nodejs.org/api/path.html

**Comment by totorelmatador** [comment]
I am working on Visual Studio Code on a Windows, but I have installed Ubuntu 18.04.1 LTS, and I use a Linux terminal on VSCode (wsl). 
Thank you for your answer, but even if I use `path.win32.basename('C:\\temp\\ThePdfIWant.pdf)` I obtain the same error...

**Comment by basia-scibior** [comment]
@totorelmatador Did you resolve this problem?

**Comment by yakovmeister** [comment]
Hi everyone, I have updated the read me file to address this concern. As for the path issue in windows, it would be hard for me to troubleshoot that one as I'm currently using linux. Also, it would be helpful if you can post your node version so I can troubleshoot and possibly update it on my free time. Thanks.

**Comment by yakovmeister** [comment]
One suggestion for the path issue: try using relation paths. I might probably work.
