### ISSUE TITLE
Converting more than one slide at a time fails

### ISSUE THREAD

**Issue by friksa** [yakovmeister/pdf2image#73]
On Mac OS 10.15.5 when I use the same PDF, I am able to convert each slide to a PNG, one slide at a time.  However, if I specify more than one slide at a time or all slides, I get this error:

````
(node:88658) UnhandledPromiseRejectionWarning: Error: Command failed: GPL Ghostscript 9.52: Unrecoverable error, exit code 1
gm convert: "gs" "-q" "-dBATCH" "-dSAFER" "-dMaxBitmap=50000000" "-dNOPAUSE" "-sDEVICE=ppmraw" "-dTextAlphaBits=4" "-dGraphicsAlphaBits=4" "-r100x100" "-dFirstPage=18446744073709551615" "-dLastPage=18446744073709551615" "-sOutputFile=/var/folders/rw/mlnbjynj2qsc7bfjvx_wdxth0000gn/T/gmm0uuxL" "--" "/var/folders/rw/mlnbjynj2qsc7bfjvx_wdxth0000gn/T/gm8LT82h" "-c" "quit".
gm convert: Postscript delegate failed (/var/folders/rw/mlnbjynj2qsc7bfjvx_wdxth0000gn/T/gmpqgZXA).

    at ChildProcess.onExit (/Users/fstrecker/dev-ng/gw-server/node_modules/gm/lib/command.js:301:17)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:88658) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:88658) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

It seems that this also has an uncaught error that should be caught and dealt with to avoid the server being killed.

Debian 10 has the exact same issue.  Just confirmed it.

**Comment by friksa** [comment]
Was totally my fault for not noticing convertBulk vs convert.
