### ISSUE TITLE
Conversion fails when image size is large

### ISSUE THREAD

**Issue by friksa** [yakovmeister/pdf2image#76]
When a single PDF slide is too big, the conversion fails with this error in the logs:
```
2|main           | { Error: Command failed: GPL Ghostscript 9.26: Unrecoverable error, exit code 1
2|main           | gm identify: "gs" "-q" "-dBATCH" "-dSAFER" "-dMaxBitmap=50000000" "-dNOPAUSE" "-sDEVICE=pnmraw" "-dTextAlphaBits=4" "-dGraphicsAlphaBits=4" "-r72x72" "-sOutputFile=/tmp/gmcnskDT" "--" "/tmp/gmOBTdFt" "-c" "quit".
2|main           | gm identify: Unexpected end-of-file (/tmp/gmcnskDT).
2|main           | gm identify: Request did not return an image.
2|main           |     at ChildProcess.onExit (/opt/gw-server/node_modules/gm/lib/command.js:301:17)
2|main           |     at ChildProcess.emit (events.js:198:13)
2|main           |     at maybeClose (internal/child_process.js:982:16)
2|main           |     at Socket.stream.socket.on (internal/child_process.js:389:11)
2|main           |     at Socket.emit (events.js:198:13)
2|main           |     at Pipe._handle.close (net.js:607:12) code: 1, signal: null }
```

How can the minimum slide config be changed so that any size image / page can be converted?  Presumably: -dMaxBitmap=50000000

**Comment by yakovmeister** [comment]
I do not have direct access to gs, this cannot be solved as of now. Closing this.

**Comment by friksa** [comment]
Moved to pdftocairo as it fixes all the issues.

**Comment by jose920405** [comment]
Same issue here. Not even with with a big file. A PDF of `17 KB` with 1 single page.
