### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by zombiestruck** [yakovmeister/pdf2image#79]
(node:53784) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:784:11)
    at Socket._write (net.js:796:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at ReadStream.ondata (_stream_readable.js:695:22)
    at ReadStream.emit (events.js:310:20)
    at ReadStream.Readable.read (_stream_readable.js:493:10)

**Comment by yakovmeister** [comment]
@zombiestruck will you be able to be more informative? 

How can this issue be replicated?
What version of node are you using?
How large is the pdf you are trying to process?

**Comment by carlos97** [comment]
> 
> 
> @zombiestruck will you be able to be more informative?
> 
> How can this issue be replicated?
> What version of node are you using?
> How large is the pdf you are trying to process?

Hi, i have the same issue processing a 3319 KB file in node 12

**Comment by Itee** [comment]
Same here !

> (node:460) UnhandledPromiseRejectionWarning: Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%p" "C:\XXX\pdfs\20200227091129.pdf" this most
likely means the gm/convert binaries can't be found
(node:460) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Socket.Writable.write (_stream_writable.js:303:10)
    at ReadStream.ondata (_stream_readable.js:719:22)
    at ReadStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)

Using : 
node@14.15.1
pdf2pic@1.3.12

**Comment by Itee** [comment]
Same using pdf2pic@2.1.4

> Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "-density" "100x100" "-quality" "75" "-[0]" "-resize" "600x600!" "-compress" "jpeg" "./images/untitled.1.png" this most likely means the gm/convert binaries can't be
 found

**Comment by yakovmeister** [comment]
@Itee , you have to ensure that the required dependency is installed. More on that [here](https://github.com/yakovmeister/pdf2image/blob/master/docs/gm-installation.md)

**Comment by smppandi1998** [comment]
Still im facing this issue ,please help me @yakovmeister @Itee @carlos97 @zombiestruck @yhanwen 

(node:9580) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at ReadStream.ondata (internal/streams/readable.js:719:22)
    at ReadStream.emit (events.js:315:20)
    at ReadStream.Readable.read (internal/streams/readable.js:519:10)
    at flow (internal/streams/readable.js:992:34)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by brianMxBm** [comment]
Still facing this issue as well. I have the deps as lambda layers as stated by the dep installation steps.
